apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: prometheus-server
  ports:
  - name: http
    port: 9090
    protocol: TCP
#  type: NodePort
#  ports:
#    - port: 8080
#      targetPort: 9090
#      nodePort: 30000
