apiVersion: v1
kind: Service
metadata:
  name: static-website
  namespace: static-website
  labels:
    component: web
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP