### nginx-os-pv.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      - name: netshoot-slicar
        image: nicolaka/netshoot
        command: [ "/bin/bash" ]
        args: [ "-c", "while true; do echo 'hodor' ; sleep 60;done" ]

# In case of log to file, or you need to host img. you will need pv.
#      volumes:
#      - name: csi-data-cinderplugin1
#        persistentVolumeClaim:
#          claimName: csi-pvc-cinderplugin1
#          readOnly: false
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: csi-pvc-cinderplugin1
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
