apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: controller-logging
spec:
  ports:
  - port: 8080
    name: http
  - port: 8443
    name: https
  selector:
    app: controller-logging
