apiVersion: v1
kind: Secret
metadata:
  name: elastalert-rules-secret
  namespace: logging
type: Opaque
stringData:
  example_frequency.yaml: |-
    name: "a"
    type: "frequency"
    index: "user-a*"
    is_enabled: true
    num_events: 2
    run_every:
      seconds: 10
    buffer_time:
      minutes: 15
    realert:
      minutes: 5
    terms_size: 50
    timeframe:
      minutes: 5
    timestamp_field: "@timestamp"
    timestamp_type: "iso"
    use_strftime_index: false
    alert_subject: "Test {} 123 aa☃"
    alert_subject_args:
      - "message"
      - "@log_name"
    alert_text: "Test {}  123 bb☃"
    alert_text_args:
      - "message"
    filter:
      - query:
          query_string:
            query: "@timestamp:*"
    alert: post
    http_post_url: http://controller-logging:8080/alarm?id=a
  example_flat.yml: |-
    name: "b"
    type: "frequency"
    index: "user-a*"
    is_enabled: true
    num_events: 2
    run_every:
      seconds: 10
    buffer_time:
      minutes: 15
    realert:
      minutes: 5
    terms_size: 50
    timeframe:
      minutes: 5
    timestamp_field: "@timestamp"
    timestamp_type: "iso"
    use_strftime_index: false
    alert_subject: "Test {} 123 aa☃"
    alert_subject_args:
      - "message"
      - "@log_name"
    alert_text: "Test {}  123 bb☃"
    alert_text_args:
      - "message"
    filter:
      - query:
          query_string:
            query: "@timestamp:*"
    alert: post
    http_post_url: http://controller-logging:8080/alarm?id=b
